### PR TITLE
use progress list from look-and-feel

### PR DESCRIPTION
**Pull request by dtaylor7**
[DIV-3925 - Replace reform-pattern-library as its now unsupported](https://tools.hmcts.net/jira/browse/DIV-3925)

Use progress list from look-and-feel

### CODE REVIEW

**Comment by hosainnet** [comment]
@tchow8 had to add back some CSS from the reform-lib, not sure if we need to do the same in DN?
https://github.com/hmcts/div-respondent-frontend/pull/222

**Comment by dtaylor7** [comment]
> @tchow8 had to add back some CSS from the reform-lib, not sure if we need to do the same in DN?
> [hmcts/div-respondent-frontend#222](https://github.com/hmcts/div-respondent-frontend/pull/222)

oh did we forget to add this on RFE? https://github.com/hmcts/div-decree-nisi-frontend/pull/231/files#diff-bbefc3ad9404805c599babc090218242R5

**Comment by tchow8** [comment]
text-reference-number class was missing, from https://github.com/hmcts/reform-pattern-library/blob/master/app/sass/components/_components-text.scss which I'm told will be deprecated?
Don't see the text-reference-number class in the progress-list.scss?

**Comment by dtaylor7** [comment]
@tchow8 not sure how that happened, however if its anything to do with the progress list it would be usful to have in the look-and-feel repo with rest of progress-list css https://github.com/hmcts/look-and-feel/blob/master/assets/scss/look-and-feel/progress-list.scss

**Comment by tchow8** [comment]
Nothing to do with progress list I think, a separate reform-attern-library component. Good shout though, I'll open a PR on look-and-feel with the text module.

**Comment by hosainnet** [comment]
Thanks @tchow8  - please reference this PR in the look-and-feel PR so we can merge this after look-and-feel is merged 👍

**Comment by tchow8** [comment]
Opened PR https://github.com/hmcts/look-and-feel/pull/113
@dtaylor7 Can you add to the main.scss, @import 'look-and-feel/text-reference.scss'; when that gets merged please.
I think "@hmcts/look-and-feel": "^2.0.2" should pick up 2.1.1

**Comment by dtaylor7** [comment]
> 👍 merge merge

its waiting for QA to test all progress pages and merge

**Comment by nsingamsetty** [comment]
This is missed to merge in previous release. Merging now on behalf of Micheal

**Pull request merged**
